src/java/controlador/UsuarioController.java
package controlador;

import modelo.BaseDeDatos;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import modelo.Usuario;

/**
 * Clase que controla la navegación de las opciones de usuarios
 *
 * @author guzman6001
 */
@ManagedBean(name = "usuarioController") // or @ManagedBean(name="user")  
@SessionScoped
public class UsuarioController implements Serializable {

    private String nombre;
    private String apellido;
    private String password;
    private String username;
    private boolean loggedIn;

    /**
     * Obtener usuarios en base de datos para mostrarlos en la vista
     *
     * @return Usuarios en un arrayList
     */
    public ArrayList getUsuarios() {
        return BaseDeDatos.getUsuarios();
    }

    // NAVEGACION
    /**
     * Autenticación.
     *
     * @return regresa la redirección correspondiente
     */
    public String autenticar() {
        Usuario u = new Usuario(username, password, null, null);
        u = BaseDeDatos.getUsuario(u);
        if (u != null) {
            loggedIn = true;
            nombre = u.getNombre();
            apellido = u.getApellido();
            return "/seguro/index.xhtml";
        }

        // ERROR de LOGIN
        FacesMessage msg = new FacesMessage("No se encontró usuario o contraseña es incorrecta.", "ERROR MSG");
        msg.setSeverity(FacesMessage.SEVERITY_ERROR);
        FacesContext.getCurrentInstance().addMessage(null, msg);
        return "/login.xhtml";
    }

    public String inicio() {
        System.out.println("AUTENTICANDO...\nRUTA_DE_BASE_DE_DATOS: "+System.getProperty("user.dir"));
        if (loggedIn) {
            return "/seguro/index.xhtml";
        }
        return "/login.xhtml";
    }

    public String salir() {
        loggedIn = false;
        FacesMessage msg = new FacesMessage("Sesión finalizada", "INFO MSG");
        msg.setSeverity(FacesMessage.SEVERITY_INFO);
        FacesContext.getCurrentInstance().addMessage(null, msg);

        return "/login.xhtml";
    }
    
    /**
     * Agregar un usuario en el sistema, captura los parámetros en la vista y
     * los envía a la base de datos para su registro.
     *
     * @return redirección correspondiente
     */
    public String agregarUsuario() {
        BaseDeDatos.agregarUsuario(new Usuario(username, password, nombre, apellido));
        loggedIn = true;
        return "/seguro/index.xhtml";
    }
    
    public String creditos() {
        if (loggedIn) {
            return "/seguro/creditos.xhtml";
        }
        return "/creditos.xhtml";
    }
    
    public String ayuda() {
        if (loggedIn) {
            return "/seguro/ayuda.xhtml";
        }
        return "/ayuda.xhtml";
    }
    // VALIDACIONES:
    /**
     * valida cadena común
     *
     * @param arg0
     * @param arg1
     * @param arg2 El campo
     * @throws ValidatorException
     */
    public void validarStringNormal(FacesContext arg0, UIComponent arg1, Object arg2) throws ValidatorException {
        String campo = (String) arg2;
        if (campo.length() < 1 || campo.length() > 16) {
            throw new ValidatorException(new FacesMessage("El campo debe tener entre 1 y 16 caracteres"));
        }
        Pattern pat = Pattern.compile("^[a-zA-ZáéíóúÁÉÍÓÚÑñ ]*$");
        Matcher mat = pat.matcher(campo);
        if (!mat.matches()) {
            throw new ValidatorException(new FacesMessage("El campo no debe poseer caracteres especiales, ni números."));
        }
    }

    public void validarUsername(FacesContext arg0, UIComponent arg1, Object arg2) throws ValidatorException {
        validarStringAlfanumerico(arg0, arg1, arg2);
        String campo = (String) arg2;
        Usuario u = BaseDeDatos.getUsuarioByUsername(campo);
        if (u != null) {
            throw new ValidatorException(new FacesMessage("El nombre de usuario <" + campo + "> ya existe, debe seleccionar otro."));
        }
    }

    public void validarStringAlfanumerico(FacesContext arg0, UIComponent arg1, Object arg2) throws ValidatorException {
        String campo = (String) arg2;
        if (campo.length() < 1 || campo.length() > 16) {
            throw new ValidatorException(new FacesMessage("El campo debe tener entre 1 y 16 caracteres"));
        }
        Pattern pat = Pattern.compile("^[a-zA-Z0-9_]*$");
        Matcher mat = pat.matcher(campo);
        if (!mat.matches()) {
            throw new ValidatorException(new FacesMessage("El campo solo acepta letras (A-Z, a-z) y números (0-9)."));
        }
    }
    
    // PROPIEDADES (GETTER Y SETTER):
    public boolean isLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }
    
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }
    
    public String getFullname() {
        return nombre+" "+apellido;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}

web/seguro/ayuda.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition  template="/seguro/layout.xhtml"> 
            <ui:define name="content">
                <h:form>
                    <p:accordionPanel>
                        <p:tab title="Conceptos Básicos">
                            <p:tabView orientation="left" >
                                <p:tab title="¿Qué son Tickets?">
                                    <h:panelGrid cellpadding="10">
                                        <h:outputText 
                                            value="Los tickets, también llamados, incidentes o issues, son tareas que se deben atender dentro de un proyecto. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id tempus dolor. Vivamus ullamcorper ultricies nulla, eget gravida mauris finibus non. Cras faucibus mi finibus, semper sapien vel, malesuada sem. Nam sapien est, porttitor ac dui vitae, eleifend ornare sem. Cras orci nisi, placerat eget interdum in, malesuada ac orci. Proin ultrices, turpis sit amet feugiat ornare, urna urna efficitur tortor, eget tincidunt nibh sapien ac turpis. Morbi pretium sapien ut condimentum rhoncus. Morbi at justo faucibus, iaculis enim efficitur, mollis nisl. Nullam tempor nec sem sed ornare. Sed pellentesque nisl mollis risus egestas sollicitudin. Phasellus augue purus, hendrerit non suscipit quis, sollicitudin nec est." />
                                    </h:panelGrid>
                                </p:tab>
                                <p:tab title="¿Qué es un sistema de administración de incidentes?">
                                    <h:panelGrid cellpadding="10">
                                        <h:outputText
                                            value="Un sistema de seguimiento de incidentes (denominado en inglés como issue tracking system, trouble ticket system o incident ticket system) es un paquete de software que administra listas de incidentes. Proin tincidunt ut elit at consequat. Mauris a erat sed augue pellentesque blandit. In at arcu lorem. Aliquam vel lorem consequat, luctus felis a, viverra eros. Aliquam a lacus vitae ex sodales imperdiet. Nulla neque massa, molestie non sagittis at, volutpat posuere est. Morbi eu est ex. Suspendisse ultricies pharetra diam a facilisis. Fusce vitae molestie metus. Sed nec convallis magna. Mauris enim lorem, finibus in lacinia in, feugiat sit amet nisl. Quisque vehicula fringilla porttitor. Duis porta ipsum mollis enim egestas sagittis. In lobortis velit in nisi hendrerit bibendum quis nec nunc." />
                                    </h:panelGrid>
                                </p:tab>
                            </p:tabView>
                        </p:tab>
                        <p:tab title="Callia">
                            <p:tabView orientation="left" >
                                <p:tab title="¿Qué es Callia?">
                                    <h:panelGrid cellpadding="10">
                                        <h:outputText value="Callia es un sistema de administración de tickets. Sed imperdiet rutrum magna, vitae posuere mi aliquam id. Pellentesque felis leo, pellentesque et imperdiet quis, condimentum a magna. Etiam malesuada eleifend nulla, sit amet tempor justo maximus vitae. Vestibulum aliquam et ipsum quis accumsan. Duis eleifend augue orci. Sed vitae est leo. Vestibulum malesuada nisi mi, quis ornare orci hendrerit sit amet. In in blandit dui. Ut mollis ante urna, nec condimentum lacus iaculis et. Duis fermentum, sapien ut aliquet laoreet, diam sapien consequat nibh, at lobortis lacus libero id elit." />
                                    </h:panelGrid>
                                </p:tab>
                                <p:tab title="¿Para que puedo utilizar Callia?">
                                    <h:panelGrid cellpadding="10">
                                        <h:outputText
                                            value="Callia permite la administración de tareas, por lo tanto puede ser util para individales, pequeños grupos y grupos amplios de personas que trabajen en uno o múltiples proyectos. Donec euismod odio id egestas faucibus. Donec pharetra, velit eget fringilla molestie, metus arcu sodales ipsum, vitae gravida nulla magna sit amet nunc. Donec vitae elit in turpis ullamcorper placerat aliquet ullamcorper massa. In viverra erat non enim ultricies scelerisque. Nullam ac venenatis ipsum, sit amet pellentesque est. Vestibulum elementum tincidunt sodales. Vivamus congue vitae dolor non molestie. Maecenas nec metus eleifend, auctor ex vitae, pretium purus. Mauris consectetur a elit ac commodo. Vivamus euismod laoreet faucibus. Suspendisse sit amet rutrum quam. Vestibulum lorem tortor, lobortis nec metus tempor, ultrices bibendum urna. Integer eget interdum elit. Phasellus eget ex sollicitudin, luctus ante quis, bibendum est." />
                                    </h:panelGrid>
                                </p:tab>
                            </p:tabView>
                        </p:tab>
                    </p:accordionPanel>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/seguro/configuracion.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition  template="/seguro/layout.xhtml"> 
            <ui:define name="content">
                <h:form>
                    <p:panel header="#{mensaje.configuracion}">
                        <p:messages autoUpdate="true"/>
                        <h:panelGrid id="grid" columns="2" cellpadding="5">
                            <h:outputText value="#{mensaje.idioma}" style="font-weight:bold"/>
                            <h:selectOneMenu value="#{localizacion.locale}" onchange="submit()"  
                                             valueChangeListener="#{localizacion.localeChanged}">
                                <f:selectItems value="#{localizacion.countries}"  />
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </p:panel>
                </h:form>
            </ui:define>  
        </ui:composition>
    </h:body>
</html>


web/seguro/crearticket.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition  template="/seguro/layout.xhtml"> 
            <ui:define name="content">
                <div id="login">
                    <h:form id="crear-ticket-form">
                        <p:panel header="#{mensaje.nuevoticket}">
                            <h:panelGrid id="grid" columns="3" cellpadding="5">

                                <h:outputText value="#{mensaje.title}" style="font-weight:bold"/>
                                <p:inputText value="#{ticketController.titulo}" id="titulo" validator="#{ticketController.validarNoVacio}"/>
                                <p:message for="titulo" />

                                <h:outputText value="#{mensaje.tipo}" style="font-weight:bold"/>
                                <p:selectOneButton id="tipo" value="#{ticketController.tipo}" validator="#{ticketController.validarNoVacio}">
                                    <f:selectItem itemLabel="Tarea" itemValue="Tarea" />
                                    <f:selectItem itemLabel="Mejora" itemValue="Mejora" />
                                    <f:selectItem itemLabel="Propuesta" itemValue="Propuesta" />
                                    <f:selectItem itemLabel="Error" itemValue="Error" />
                                </p:selectOneButton>
                                <p:message for="tipo" />
                                
                                <h:outputText value="#{mensaje.prioridad}" style="font-weight:bold"/>
                                <p:selectOneButton id="prioridad" value="#{ticketController.prioridad}" validator="#{ticketController.validarNoVacio}">
                                    <f:selectItem itemLabel="Trivial" itemValue="Trivial" />
                                    <f:selectItem itemLabel="Menor" itemValue="Menor" />
                                    <f:selectItem itemLabel="Mayor" itemValue="Mayor" />
                                    <f:selectItem itemLabel="Crítica" itemValue="Crítica" />
                                </p:selectOneButton>
                                <p:message for="prioridad" />

                                <h:outputLabel value="#{mensaje.descripcion}" style="font-weight:bold"/>
                                <p:inputTextarea value="#{ticketController.descripcion}" id="descripcion" validator="#{ticketController.validarNoVacio}" />
                                <p:message for="descripcion" />
                            </h:panelGrid>
                            <h:commandButton id="button" value="Crear" action="#{ticketController.crearticket}"/>
                        </p:panel>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/seguro/creditos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition  template="/seguro/layout.xhtml"> 
            <ui:define name="content">
               <h:form>
                    <p:panelGrid style="margin-top:20px">
                        <f:facet name="header">
                            <p:row>
                                <p:column colspan="3">#{mensaje.creditos}</p:column>
                            </p:row>
                        </f:facet>
                        <p:row>
                            <p:column style="font-weight: bold;" rowspan="2">Desarrollo</p:column>
                            <p:column colspan="2">Laura Torres</p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2">Héctor Guzmán</p:column>
                        </p:row>
                        <p:row>
                            <p:column style="font-weight: bold;" rowspan="6">Sitios web consultados</p:column>
                            <p:column>Manejo de sesiones</p:column>
                            <p:column>
                                <a href="http://www.itcuties.com/j2ee/jsf-2-login-filter-example/" target="_blank">itcuties.com</a>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>Base de Datos</p:column>
                            <p:column>
                                <a href="http://www.db4o.com/about/productinformation/resources/db4o-6.3-tutorial-java.pdf" target="_blank">Tutorial DB4O</a>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>Validadares JSF</p:column>
                            <p:column>
                                <a href="http://chuwiki.chuidiang.org/index.php?title=Validar_campos_de_formularios_con_JSF" target="_blank">chuidiang.org</a>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>PrimeFaces</p:column>
                            <p:column>
                                <a href="http://www.primefaces.org/showcase/index.xhtml" target="_blank">primefaces.org</a>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>Formatear Fechas</p:column>
                            <p:column>
                                <a href="http://www.aprendiendojava.com.ar/index.php?topic=55.0" target="_blank">aprendiendojava.com.ar</a>
                             </p:column>
                        </p:row>
                        <p:row>
                            <p:column>Íconos</p:column>
                            <p:column>
                                <a href="http://api.jqueryui.com/theming/icons/" target="_blank">Íconos JQuery</a>
                             </p:column>
                        </p:row>
                    </p:panelGrid>
                </h:form>
            </ui:define>
      </ui:composition>
    </h:body>
</html>

web/seguro/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>#{mensaje.titulo}</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
        <link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css' />
    </h:head>

    <h:body> 
        <div id="head">
            <h:panelGrid columns="2" cellpadding="10">
                <p:layoutUnit position="west" size="60%" style="text-align: left;" >
                    <ui:insert name="head">
                        <ui:include src="/header.xhtml"/>
                    </ui:insert>
                </p:layoutUnit>

                <p:layoutUnit position="center" style="text-align: right;">
                    <h:panelGrid columns="2" cellpadding="10">
                    <p:panel>#{usuarioController.fullname}</p:panel>   
                    <p:clock  pattern="dd.MM.yyyy hh:mm:ss" />
                    </h:panelGrid>
                </p:layoutUnit>
            </h:panelGrid>
        </div>

        <div id="menu">
            <ui:insert name="menu">
                <ui:include src="/seguro/menu.xhtml"/>
            </ui:insert>
        </div>

        <div id="body">
            <ui:insert name="content"/>
        </div>
        <ui:debug/>
    </h:body>
</html>

web/seguro/menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head><title>IGNORED</title></head>
    <body>
        <ui:composition>
            <div class="menu">
                <h:form>
                    <p:tabMenu activeIndex="#{param.i}">
                    <p:menuitem value="#{mensaje.inicio}" action="#{usuarioController.inicio}"  icon="ui-icon-home">
                        <f:param name="i" value="0" />
                    </p:menuitem>
                    <p:menuitem action="#{usuarioController.creditos}" value="#{mensaje.creditos}"  icon="ui-icon-person">
                        <f:param name="i" value="1" />
                    </p:menuitem>
                    <p:menuitem action="#{usuarioController.ayuda}" value="#{mensaje.ayuda}"  icon="ui-icon-help">
                        <f:param name="i" value="2" />
                    </p:menuitem>
                    <p:menuitem  action="#{navegacionController.configuracion}" value="#{mensaje.configuracion}"  icon="ui-icon-wrench">
                        <f:param name="i" value="3" />
                    </p:menuitem>
                    <p:menuitem action="#{usuarioController.salir}" value="#{mensaje.salir}"  icon="ui-icon-circle-close">
                        <f:param name="i" value="4" />
                    </p:menuitem>
                </p:tabMenu>
                </h:form>
            </div>
        </ui:composition>
    </body>
</html>